name: Sync Branch on Push

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Fetch all branch
        run: git fetch --all
      - name: Check branch
        run: git branch --all
      - name: Checkout Origin/main-site-A
        run: git checkout origin/main-site-A
      - name: Sync to origin/main-site-A
        run: git merge origin/main
