name: Sync Branch

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write # ถ้าจะ push docker ไป ghcr

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync site A
        run: git push origin main:main-site-A --force

      - name: Sync site B
        run: git push origin main:main-site-B --force

      - name: Build Docker Image
        run: docker build -t ghcr.io/${{ github.repository }}:latest .

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker Image
        run: docker push ghcr.io/${{ github.repository }}:latest

      - name: Dialog Message
        run: echo "Docker build and push success!"
